name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.4
      - run: corepack enable
      - run: corepack yarn install --frozen-lockfile
      - run: corepack yarn test
